In [11]:
# import the necessary packages
import numpy as np
 
# Malisiewicz et al.
def non_max_suppression_fast(boxes, overlapThresh):
    # if there are no boxes, return an empty list
    if len(boxes) == 0:
        return []
 
    # if the bounding boxes integers, convert them to floats --
    # this is important since we'll be doing a bunch of divisions
    if boxes.dtype.kind == "i":
        boxes = boxes.astype("float")
 
    # initialize the list of picked indexes	
    pick = []
 
    # grab the coordinates of the bounding boxes
    x1 = boxes[:,0]
    y1 = boxes[:,1]
    x2 = boxes[:,2]
    y2 = boxes[:,3]
 
    # compute the area of the bounding boxes and sort the bounding
    # boxes by the bottom-right y-coordinate of the bounding box
    area = (x2 - x1 + 1) * (y2 - y1 + 1)
    #idxs = np.argsort(y2)
    idxs = np.argsort(area)
 
    # keep looping while some indexes still remain in the indexes
    # list
    while len(idxs) > 0:
        # grab the last index in the indexes list and add the
        # index value to the list of picked indexes
        last = len(idxs) - 1
        i = idxs[last]
        pick.append(i)
 
        # find the largest (x, y) coordinates for the start of
        # the bounding box and the smallest (x, y) coordinates
        # for the end of the bounding box
        xx1 = np.maximum(x1[i], x1[idxs[:last]])
        yy1 = np.maximum(y1[i], y1[idxs[:last]])
        xx2 = np.minimum(x2[i], x2[idxs[:last]])
        yy2 = np.minimum(y2[i], y2[idxs[:last]])
 
        # compute the width and height of the bounding box
        w = np.maximum(0, xx2 - xx1 + 1)
        h = np.maximum(0, yy2 - yy1 + 1)
 
        # compute the ratio of overlap
        overlap = (w * h) / area[idxs[:last]]
 
        # delete all indexes from the index list that have
        idxs = np.delete(idxs, np.concatenate(([last],
            np.where(overlap > overlapThresh)[0])))
 
    # return only the bounding boxes that were picked using the
    # integer data type
    return boxes[pick].astype("int")

In [85]:
import numpy as np

boxes = np.array([544,133,660,443,
                 569,102,663,278,
                 555,114,631,256,
                 535,232,611,430])

boxes = np.array([ 273,152,495,498,
                387,64,657,498,
                524,79,724,449,
                451,55,579,213,
                562,87,710,311,
                436,64,610,320,
                302,173,408,397,
                445,135,577,419,
                575,69,663,189,
                537,131,665,395,
                531,229,657,457])


boxes = boxes.reshape(11,4)
print(boxes)
print('.....')
bbox = non_max_suppression_fast(boxes, 0.90)
print(bbox)

[[273 152 495 498]
 [387  64 657 498]
 [524  79 724 449]
 [451  55 579 213]
 [562  87 710 311]
 [436  64 610 320]
 [302 173 408 397]
 [445 135 577 419]
 [575  69 663 189]
 [537 131 665 395]
 [531 229 657 457]]
.....
[[387  64 657 498]
 [273 152 495 498]
 [524  79 724 449]]


In [76]:
import pandas as pd
from shutil import copy
import os



df = pd.read_csv('z:\OC_RESINET\process\ResiIndoor05-Pond5\snapshot.txt',header=None)
for line in enumerate(df.values):
    line = str(line)
    line = line.split('\\')
    drive = line[0].split('[')
    filename = line[10].split(']')
    src = drive[1]+'\\' + line[1]+'\\' +line[2]+'\\' +line[3]+'\\' +line[4]+'\\' +line[5]+'\\' +line[6]+'\\' +line[7]+'\\' +line[8]+'\\' +filename[0]
    dst = drive[1]+'\\' +line[1]+'\\' +line[2]+'\\' +line[3]+'\\' +line[4]+'\\' +line[5]+'\\' +line[6]+'\\' +line[7]+'\\' +"_snapshot"+'\\' +line[8]+'_'+filename[0]
    #copy(src,dst)
    copy('z:\\OC_RESINET\\process\\ResiIndoor05-Pond5\\' + line[8] +  '\\output_00001.jpg',
         'z:\\OC_RESINET\\process\\ResiIndoor05-Pond5\\_snapshot\\'+ line[8] +'output_00001.jpg')    
    print(line[8])
    #filename = os.path.basename(str(line))
    #filename = filename[0:16]
    #print(os.path.splitext(str(line),'\'))
    

front_door_001
front_door_002
front_door_003
front_door_004
front_door_005
front_door_006
front_door_007
front_door_008
front_door_009
front_door_010
front_door_011
front_door_012
front_door_013
front_door_014
front_door_015
front_door_016
front_door_017
front_door_018
indoor_001
indoor_001_falseAlarm
indoor_002
indoor_002_falseAlarm
indoor_003
indoor_004
indoor_005
indoor_006
indoor_007
indoor_008
indoor_009
indoor_010
indoor_011
indoor_012
indoor_013
indoor_014
indoor_015
indoor_016
indoor_017
indoor_018
indoor_019
indoor_020
indoor_021
indoor_022
indoor_023
indoor_024
indoor_025
indoor_026
indoor_027
indoor_028
indoor_029
indoor_030
indoor_031
indoor_032
indoor_033
indoor_034
indoor_035
indoor_036
indoor_037
indoor_038
indoor_039
indoor_040
indoor_041
indoor_042
indoor_043
indoor_044
indoor_045
indoor_046
indoor_047
indoor_048
indoor_049
indoor_050
indoor_051
indoor_052
indoor_053
indoor_054
indoor_055
indoor_056
indoor_057
indoor_058
indoor_059
indoor_060
indoor_door_001
indoor_doo