In [20]:
import queue
import numpy as np
import datetime

q = queue.Queue()
im = np.ones((1,10))
#data = list()


for i in range(5):
    q.put([i,datetime.datetime.now(),im])

while not q.empty():
    i,now,im = q.get()
    print(i)
    print(now)
    print(im)

0
2017-07-10 13:45:10.429750
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
1
2017-07-10 13:45:10.429750
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
2
2017-07-10 13:45:10.429750
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
3
2017-07-10 13:45:10.429750
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
4
2017-07-10 13:45:10.429750
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [22]:
def get_primes(number):
    while True:
        if is_prime(number):
            yield number
        number += 1

In [28]:
#generator = np.array(10)
detector = get_primes(1)

In [29]:
print(detector)

<generator object get_primes at 0x0000000006878410>
